name: MercerStreet
favicon: null
layout_spectrum: 0.75204
typography_spectrum: 0.029154311399906874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050503'
    - '#757575'
    - '#b6b6b6'
    - '#464645'
  brandStrength: 0.5
  lightness: 0.893454190576449
  saturation: 0.9211743581108749
  rhythmicContrast: 0.46778391185216606
purpose: []
